### ISSUE TITLE
what values to put in this program

### ISSUE THREAD

**Issue by avnet613** [vpervenditti/gearbest-api#2]
I don't know what is ikid and page.
thank you

**Comment by davtur19** [comment]
From the Gearbest Api docs:
> Your linkid generated from "custom link generator"

**Comment by avnet613** [comment]
I can't find the gearbest api docs.
can you give me links?

**Comment by dariotarantini** [comment]
You can find them at this link

https://affiliate.gearbest.com/home/api/detail
